*** empty log message ***

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2559,9 +2559,11 @@ case $host in
     ;;
   *-*-cygwin*)
     cygwin=yes
+    windows=yes
     ;;
   *-*-mingw32*)
     mingw=yes
+    windows=yes
     ;;
   *-hp-hpux*)
     SO_LIB_SUFFIX=".sl"
@@ -2636,7 +2638,7 @@ fi
 # total stack size on NT defaults to 128MB (will be added to LDFLAGS later):
 CYGWIN_STACKSIZE=134217728
 
-build_shared_libs=if-not-cygwin
+build_shared_libs=if-not-windows
 #build_shared_libs=yes
 #build_shared_libs=no
 
@@ -2654,6 +2656,10 @@ else
    TK_CFLAGS=
 fi
 TK_LIBS=
+
+#
+# FIXME add BLT!!!!!
+#
 
 # for MPI
 MPI_CFLAGS=
@@ -3769,7 +3775,7 @@ fi
 done
 test -n "$WISH" || WISH="nope"
 
-if test "$WISH" = nope -a ! "$PLOVE_EMBED_TCL" = yes; then
+if test "$WISH" = nope -a ! "$EMBED_TCL_CODE" = yes; then
    { echo "$as_me:$LINENO: WARNING: cannot find wish, part of Tcl/Tk - Plove will not work" >&5
 echo "$as_me: WARNING: cannot find wish, part of Tcl/Tk - Plove will not work" >&2;}
 fi
@@ -4744,8 +4750,8 @@ else
 echo "$as_me: error: cannot build Tcl/Tk apps, probably due to missing X11 headers -- try installing the XFree86 packages or get the X headers from the OMNeT++ site" >&2;}
    { (exit 1); exit 1; }; }
         else
-            { { echo "$as_me:$LINENO: error: cannot build Tcl/Tk apps, probably due to misconfigured or missing X11 headers or libs" >&5
-echo "$as_me: error: cannot build Tcl/Tk apps, probably due to misconfigured or missing X11 headers or libs" >&2;}
+            { { echo "$as_me:$LINENO: error: cannot build Tcl/Tk apps, probably due to misconfigured or missing X11 headers or libs. Check config.log for more info!" >&5
+echo "$as_me: error: cannot build Tcl/Tk apps, probably due to misconfigured or missing X11 headers or libs. Check config.log for more info!" >&2;}
    { (exit 1); exit 1; }; }
         fi
     else
@@ -5127,8 +5133,8 @@ fi
 #----------------------
 # If you change this setting, remember to delete the other set of libraries
 # (or at least the soft links from lib/).
-if test "$build_shared_libs" = if-not-cygwin; then
-    if test "$cygwin" = yes; then
+if test "$build_shared_libs" = if-not-windows; then
+    if test "$windows" = yes; then
         build_shared_libs=no
     else
         build_shared_libs=yes
@@ -5149,24 +5155,18 @@ fi
 # Tcl code embedding.
 #----------------------
 
-if test "$TKENV_EMBED_TCL" = yes; then
+if test "$EMBED_TCL_CODE" = yes; then
    TKENV_EMBED_SUFFIX=-e
+   GNED_EMBED_SUFFIX=-e
+   PLOVE_VARIANT=plove-exe
 else
    TKENV_EMBED_SUFFIX=
-fi
-
-if test "$GNED_EMBED_TCL" = yes; then
-   GNED_EMBED_SUFFIX=-e
-else
    GNED_EMBED_SUFFIX=
-fi
-
-if test "$PLOVE_EMBED_TCL" = yes; then
-   PLOVE_VARIANT=plove-exe
-elif test "$cygwin" = yes; then
-   PLOVE_VARIANT=plove-cyg
-else
-   PLOVE_VARIANT=plove-sh
+   if test "$cygwin" = yes; then
+      PLOVE_VARIANT=plove-cyg
+   else
+      PLOVE_VARIANT=plove-sh
+   fi
 fi
 
 
