*** empty log message ***

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -272,7 +272,7 @@ PACKAGE_STRING=
 PACKAGE_BUGREPORT=
 
 ac_unique_file="include/omnetpp.h"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX RANLIB ac_ct_RANLIB YACC LEX LEXLIB LEX_OUTPUT_ROOT MAKE DOXYGEN PERL XSLTPROC GHOSTSCRIPT CONVERT DOT GIFTRANS CXXCPP WISH OMNETPP_VERSION OMNETPP_BIN_DIR OMNETPP_INCL_DIR OMNETPP_LIB_DIR OMNETPP_BITMAP_PATH OMNETPP_SRC_DIR OMNETPP_UTILS_DIR OMNETPP_DOC_DIR OMNETPP_SAMPLES_DIR OMNETPP_TEST_DIR MYPWD NEDC MSGC NEDTOOL GNED NEDCFLAGS AS AR SHLIB_LD MAKEDEPEND A_LIB_SUFFIX SO_LIB_SUFFIX LIB_SUFFIX EXE_SUFFIX NO_TCL HAVE_DLOPEN TK_CFLAGS TK_LIBS HAVE_BLT BLT_LIBS HAVE_MPI MPI_CFLAGS MPI_LIBS SYS_LIBS XMLPARSER XML_CFLAGS XML_LIBS AKAROA_CFLAGS AKAROA_LIBS TKENV_IF_POSSIBLE GNED_IF_POSSIBLE SCALARS_IF_POSSIBLE PLOVE_IF_POSSIBLE USERIF_LIBS TKENV_EMBED_SUFFIX GNED_EMBED_SUFFIX SCALARS_EMBED_SUFFIX PLOVE_EMBED_SUFFIX OMNETPP_TKENV_DIR OMNETPP_GNED_DIR OMNETPP_SCALARS_DIR OMNETPP_PLOVE_DIR WITH_NETBUILDER WITH_PARSIM LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX RANLIB ac_ct_RANLIB YACC LEX LEXLIB LEX_OUTPUT_ROOT MAKE DOXYGEN PERL XSLTPROC GHOSTSCRIPT CONVERT DOT GIFTRANS CXXCPP WISH OMNETPP_VERSION OMNETPP_EDITION OMNETPP_BIN_DIR OMNETPP_INCL_DIR OMNETPP_LIB_DIR OMNETPP_BITMAP_PATH OMNETPP_SRC_DIR OMNETPP_UTILS_DIR OMNETPP_DOC_DIR OMNETPP_SAMPLES_DIR OMNETPP_TEST_DIR MYPWD NEDC MSGC NEDTOOL GNED NEDCFLAGS AS AR SHLIB_LD MAKEDEPEND A_LIB_SUFFIX SO_LIB_SUFFIX LIB_SUFFIX EXE_SUFFIX NO_TCL HAVE_DLOPEN TK_CFLAGS TK_LIBS HAVE_BLT BLT_LIBS HAVE_MPI MPI_CFLAGS MPI_LIBS SYS_LIBS XMLPARSER XML_CFLAGS XML_LIBS AKAROA_CFLAGS AKAROA_LIBS TKENV_IF_POSSIBLE GNED_IF_POSSIBLE SCALARS_IF_POSSIBLE PLOVE_IF_POSSIBLE USERIF_LIBS TKENV_EMBED_SUFFIX GNED_EMBED_SUFFIX SCALARS_EMBED_SUFFIX PLOVE_EMBED_SUFFIX OMNETPP_TKENV_DIR OMNETPP_GNED_DIR OMNETPP_SCALARS_DIR OMNETPP_PLOVE_DIR WITH_NETBUILDER WITH_PARSIM LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1495,12 +1495,6 @@ if test -d /usr/include/tcl8.5; then
     TK_CFLAGS="-I/usr/include/tcl8.5"
 fi
 
-if test "$cygwin" = yes; then
-    BLT_LIBS="-lBLT24 -mwindows -lwinspool"
-else
-    BLT_LIBS="-lBLT24"
-fi
-
 #----------------------
 # Read user settings (and allow override the above settings)
 #----------------------
@@ -2617,8 +2611,9 @@ if test "$CXX" = "icpc"; then
     # remark #1419: external declaration in primary source file
     # remark #383: value copied to temporary, reference to temporary used
     #
-
     #CFLAGS="$CFLAGS -wd654 -wd177 -wd869 -wd981 -wd279 -wd1572 -wd424 -wd1682 -wd1683 -wd810 -wd1418 -wd1419"
+
+    # -w1 disables all remarks
     CFLAGS="$CFLAGS -w1 -wd654 -wd177"
 fi
 
@@ -5138,6 +5133,272 @@ rm -f conftest.err conftest.$ac_objext \
    CXXFLAGS=$save_CXXFLAGS
    LIBS=$save_LIBS
 
+if test $blt_ok = no -a "$cygwin" = yes; then
+    bltlibs="-lBLT24 -mwindows -lwinspool"
+
+   save_CXXFLAGS=$CXXFLAGS
+   save_LIBS=$LIBS
+
+   CXXFLAGS="$TK_CFLAGS"
+   LIBS="$bltlibs $TK_LIBS"
+
+   echo "$as_me:$LINENO: checking for BLT 2.4 with CFLAGS=\"$TK_CFLAGS\" LIBS=\"$bltlibs $TK_LIBS\"" >&5
+echo $ECHO_N "checking for BLT 2.4 with CFLAGS=\"$TK_CFLAGS\" LIBS=\"$bltlibs $TK_LIBS\"... $ECHO_C" >&6
+
+   cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <blt.h>
+int
+main ()
+{
+Blt_NameOfVector(0);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; blt_ok=yes; BLT_LIBS=$bltlibs
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; blt_ok=no;
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+
+   CXXFLAGS=$save_CXXFLAGS
+   LIBS=$save_LIBS
+
+fi
+if test $blt_ok = no; then
+    bltlibs="-lBLT24"
+
+   save_CXXFLAGS=$CXXFLAGS
+   save_LIBS=$LIBS
+
+   CXXFLAGS="$TK_CFLAGS"
+   LIBS="$bltlibs $TK_LIBS"
+
+   echo "$as_me:$LINENO: checking for BLT 2.4 with CFLAGS=\"$TK_CFLAGS\" LIBS=\"$bltlibs $TK_LIBS\"" >&5
+echo $ECHO_N "checking for BLT 2.4 with CFLAGS=\"$TK_CFLAGS\" LIBS=\"$bltlibs $TK_LIBS\"... $ECHO_C" >&6
+
+   cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <blt.h>
+int
+main ()
+{
+Blt_NameOfVector(0);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; blt_ok=yes; BLT_LIBS=$bltlibs
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; blt_ok=no;
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+
+   CXXFLAGS=$save_CXXFLAGS
+   LIBS=$save_LIBS
+
+fi
+if test $blt_ok = no; then
+    bltlibs="-lBLT"
+
+   save_CXXFLAGS=$CXXFLAGS
+   save_LIBS=$LIBS
+
+   CXXFLAGS="$TK_CFLAGS"
+   LIBS="$bltlibs $TK_LIBS"
+
+   echo "$as_me:$LINENO: checking for BLT 2.4 with CFLAGS=\"$TK_CFLAGS\" LIBS=\"$bltlibs $TK_LIBS\"" >&5
+echo $ECHO_N "checking for BLT 2.4 with CFLAGS=\"$TK_CFLAGS\" LIBS=\"$bltlibs $TK_LIBS\"... $ECHO_C" >&6
+
+   cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <blt.h>
+int
+main ()
+{
+Blt_NameOfVector(0);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; blt_ok=yes; BLT_LIBS=$bltlibs
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; blt_ok=no;
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+
+   CXXFLAGS=$save_CXXFLAGS
+   LIBS=$save_LIBS
+
+fi
+if test $blt_ok = no; then
+    bltlibs="-lBLT2.4"
+
+   save_CXXFLAGS=$CXXFLAGS
+   save_LIBS=$LIBS
+
+   CXXFLAGS="$TK_CFLAGS"
+   LIBS="$bltlibs $TK_LIBS"
+
+   echo "$as_me:$LINENO: checking for BLT 2.4 with CFLAGS=\"$TK_CFLAGS\" LIBS=\"$bltlibs $TK_LIBS\"" >&5
+echo $ECHO_N "checking for BLT 2.4 with CFLAGS=\"$TK_CFLAGS\" LIBS=\"$bltlibs $TK_LIBS\"... $ECHO_C" >&6
+
+   cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <blt.h>
+int
+main ()
+{
+Blt_NameOfVector(0);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; blt_ok=yes; BLT_LIBS=$bltlibs
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; blt_ok=no;
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+
+   CXXFLAGS=$save_CXXFLAGS
+   LIBS=$save_LIBS
+
+fi
+if test $blt_ok = no; then
+    OPP_PROBLEM_PACKAGES="$OPP_PROBLEM_PACKAGES  BLT"
+    { echo "$as_me:$LINENO: WARNING: Cannot compile or link program with BLT: BLT or BLT-devel may not be installed -- check config.log for details. Plove and Scalars require BLT to build." >&5
+echo "$as_me: WARNING: Cannot compile or link program with BLT: BLT or BLT-devel may not be installed -- check config.log for details. Plove and Scalars require BLT to build." >&2;}
+    HAVE_BLT=no
+fi
 if test $blt_ok = yes; then
     HAVE_BLT=yes
     if echo 'catch {package require BLT 2.4; puts OK}; exit' | $WISH | grep OK >/dev/null; then :; else
@@ -5145,11 +5406,6 @@ if test $blt_ok = yes; then
         { echo "$as_me:$LINENO: WARNING: Tcl cannot load BLT (wish command \"package require BLT 2.4\" failed), probably BLT not installed correctly." >&5
 echo "$as_me: WARNING: Tcl cannot load BLT (wish command \"package require BLT 2.4\" failed), probably BLT not installed correctly." >&2;}
     fi
-else
-    OPP_PROBLEM_PACKAGES="$OPP_PROBLEM_PACKAGES  BLT"
-    { echo "$as_me:$LINENO: WARNING: Cannot compile or link program with BLT: BLT or BLT-devel may not be installed -- check config.log for details. Plove and Scalars require BLT to build." >&5
-echo "$as_me: WARNING: Cannot compile or link program with BLT: BLT or BLT-devel may not be installed -- check config.log for details. Plove and Scalars require BLT to build." >&2;}
-    HAVE_BLT=no
 fi
 
 # if we got through until here, enable building of the following progs:
@@ -5998,6 +6254,7 @@ fi
 
 
 
+
 #
 # Generate files
 #
@@ -6698,6 +6955,7 @@ s,@GIFTRANS@,$GIFTRANS,;t t
 s,@CXXCPP@,$CXXCPP,;t t
 s,@WISH@,$WISH,;t t
 s,@OMNETPP_VERSION@,$OMNETPP_VERSION,;t t
+s,@OMNETPP_EDITION@,$OMNETPP_EDITION,;t t
 s,@OMNETPP_BIN_DIR@,$OMNETPP_BIN_DIR,;t t
 s,@OMNETPP_INCL_DIR@,$OMNETPP_INCL_DIR,;t t
 s,@OMNETPP_LIB_DIR@,$OMNETPP_LIB_DIR,;t t
@@ -7022,6 +7280,11 @@ chmod +x src/utils/opp_test
 chmod +x src/utils/opp_makedep
 chmod +x src/utils/opp_neddoc
 
+(
+cd src/utils && cp ver.h.base ver.h && \
+echo '#define OMNETPP_RELEASE "'$OMNETPP_VERSION)'"' >>ver.h && \
+echo '#define OMNETPP_EDITION "'$OMNETPP_EDITION'"' >>ver.h
+)
 
 #----------------------
 # Check $OPP_PROBLEM_PACKAGES
