pvmex removed, etc.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1080,7 +1080,7 @@ OMNETPP_TUTORIAL_DIR="$OMNETPP_ROOT/tutorial"
 OMNETPP_TEST_DIR="$OMNETPP_ROOT/test"
 OMNETPP_BITMAP_PATH=".;./bitmaps;$OMNETPP_ROOT/bitmaps"
 
-OMNETPP_SAMPLES="dyna fddi fifo1 fifo2 hcube hist nim pvmex token demo"
+OMNETPP_SAMPLES="dyna fddi fifo1 fifo2 hcube hist nim token demo"
 
 OMNETPP_BIN_DIR="$OMNETPP_ROOT/bin"
 OMNETPP_INCL_DIR="$OMNETPP_ROOT/include"
@@ -4957,7 +4957,7 @@ fi
 #----------------------
 # Files to be generated
 #----------------------
-ac_config_files="$ac_config_files Makefile src/cmdenv/Makefile src/envir/Makefile src/gned/Makefile src/nedxml/Makefile src/nedc/Makefile src/plove/Makefile src/sim/Makefile src/tkenv/Makefile src/utils/Makefile src/utils/opp_makemake src/utils/opp_neddoc samples/dyna/Makefile samples/fddi/Makefile samples/fifo1/Makefile samples/fifo2/Makefile samples/hcube/Makefile samples/hist/Makefile samples/nim/Makefile samples/pvmex/Makefile samples/token/Makefile samples/demo/Makefile tutorial/queues/Makefile include/Makefile test/Makefile"
+ac_config_files="$ac_config_files Makefile src/cmdenv/Makefile src/envir/Makefile src/gned/Makefile src/nedxml/Makefile src/nedc/Makefile src/plove/Makefile src/sim/Makefile src/tkenv/Makefile src/utils/Makefile src/utils/opp_makemake src/utils/opp_neddoc samples/dyna/Makefile samples/fddi/Makefile samples/fifo1/Makefile samples/fifo2/Makefile samples/hcube/Makefile samples/hist/Makefile samples/nim/Makefile samples/token/Makefile samples/demo/Makefile tutorial/queues/Makefile include/Makefile test/Makefile"
 
 #----------------------
 # Substitutions.
@@ -5316,13 +5316,12 @@ do
   "samples/hcube/Makefile" ) CONFIG_FILES="$CONFIG_FILES samples/hcube/Makefile" ;;
   "samples/hist/Makefile" ) CONFIG_FILES="$CONFIG_FILES samples/hist/Makefile" ;;
   "samples/nim/Makefile" ) CONFIG_FILES="$CONFIG_FILES samples/nim/Makefile" ;;
-  "samples/pvmex/Makefile" ) CONFIG_FILES="$CONFIG_FILES samples/pvmex/Makefile" ;;
   "samples/token/Makefile" ) CONFIG_FILES="$CONFIG_FILES samples/token/Makefile" ;;
   "samples/demo/Makefile" ) CONFIG_FILES="$CONFIG_FILES samples/demo/Makefile" ;;
   "tutorial/queues/Makefile" ) CONFIG_FILES="$CONFIG_FILES tutorial/queues/Makefile" ;;
   "include/Makefile" ) CONFIG_FILES="$CONFIG_FILES include/Makefile" ;;
   "test/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/Makefile" ;;
-  *) { { echo "$as_me:5325: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:5324: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -5587,7 +5586,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:5590: creating $ac_file" >&5
+    { echo "$as_me:5589: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -5605,7 +5604,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:5608: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:5607: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -5618,7 +5617,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:5621: error: cannot find input file: $f" >&5
+           { { echo "$as_me:5620: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
