added java detection

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -644,6 +644,7 @@ SWIG
 XMKMF
 CXXCPP
 WISH
+JRE
 MPICPP
 MPICXX
 OMNETPP_RELEASE
@@ -6739,6 +6740,64 @@ echo "$as_me: WARNING: Tcl cannot load BLT (wish command \"package require BLT 2
 fi # end of Tcl tests ($NO_TCL=="" branch)
 
 #----------------------
+# Check for JRE
+#----------------------
+for ac_prog in $JRE java
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_prog_JRE+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$JRE"; then
+  ac_cv_prog_JRE="$JRE" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_prog_JRE="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+fi
+fi
+JRE=$ac_cv_prog_JRE
+if test -n "$JRE"; then
+  { echo "$as_me:$LINENO: result: $JRE" >&5
+echo "${ECHO_T}$JRE" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+  test -n "$JRE" && break
+done
+test -n "$JRE" || JRE="nope"
+
+if test "$JRE" = nope; then
+   if test "$mingw" = "yes"; then
+      OPP_PROBLEM_PACKAGES="$OPP_PROBLEM_PACKAGES  JRE (recommended)"
+      { echo "$as_me:$LINENO: WARNING: Cannot find a suitable Java Runtime Environment - The IDE requires JRE 1.5 or later. Please install it before configuring" >&5
+echo "$as_me: WARNING: Cannot find a suitable Java Runtime Environment - The IDE requires JRE 1.5 or later. Please install it before configuring" >&2;}
+   else
+      { { echo "$as_me:$LINENO: error: Cannot find a suitable Java Runtime Environment - The IDE requires JRE 1.5 or later. Please install it before configuring" >&5
+echo "$as_me: error: Cannot find a suitable Java Runtime Environment - The IDE requires JRE 1.5 or later. Please install it before configuring" >&2;}
+   { (exit 1); exit 1; }; }
+   fi
+fi
+
+#----------------------
 # Check for JDK
 #----------------------
 
@@ -8607,6 +8666,7 @@ SWIG!$SWIG$ac_delim
 XMKMF!$XMKMF$ac_delim
 CXXCPP!$CXXCPP$ac_delim
 WISH!$WISH$ac_delim
+JRE!$JRE$ac_delim
 MPICPP!$MPICPP$ac_delim
 MPICXX!$MPICXX$ac_delim
 OMNETPP_RELEASE!$OMNETPP_RELEASE$ac_delim
@@ -8636,7 +8696,6 @@ NEDTOOL!$NEDTOOL$ac_delim
 AS!$AS$ac_delim
 AR!$AR$ac_delim
 SHLIB_LD!$SHLIB_LD$ac_delim
-DLLTOOL!$DLLTOOL$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -8678,6 +8737,7 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+DLLTOOL!$DLLTOOL$ac_delim
 MAKEDEPEND!$MAKEDEPEND$ac_delim
 SHARED_LIBS!$SHARED_LIBS$ac_delim
 A_LIB_SUFFIX!$A_LIB_SUFFIX$ac_delim
@@ -8720,7 +8780,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 40; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 41; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
