added support for Intel icc compiler (Linux)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3560,8 +3560,62 @@ rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 
 fi
 if test $stdcpp_ok = no; then
-   { { echo "$as_me:$LINENO: error: standard C++ library -lstdc++ or -lcxx not found" >&5
-echo "$as_me: error: standard C++ library -lstdc++ or -lcxx not found" >&2;}
+
+   save_CXXFLAGS=$CXXFLAGS
+   save_LIBS=$LIBS
+
+   CXXFLAGS=""
+   LIBS="-lcxa"
+
+   echo "$as_me:$LINENO: checking for standard C++ lib with CFLAGS=\"\" LIBS=\"-lcxa\"" >&5
+echo $ECHO_N "checking for standard C++ lib with CFLAGS=\"\" LIBS=\"-lcxa\"... $ECHO_C" >&6
+
+   cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <iostream>
+int
+main ()
+{
+/**/;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; stdcpp_ok=yes; SYS_LIBS="-lcxa $SYS_LIBS"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; stdcpp_ok=no;
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+
+   CXXFLAGS=$save_CXXFLAGS
+   LIBS=$save_LIBS
+
+fi
+if test $stdcpp_ok = no; then
+   { { echo "$as_me:$LINENO: error: standard C++ library -lstdc++ or -lcxx or -lcxa not found" >&5
+echo "$as_me: error: standard C++ library -lstdc++ or -lcxx or -lcxa not found" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
