*** empty log message ***

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2689,10 +2689,79 @@ fi
 
 
 #----------------------
-# test for "-z allextract" (Sun) or "--whole-archive" (GNU) linker option,
+# Test if --export-dynamic or -E linker option is accepted and/or needed
+#----------------------
+# We want to be able to dynamically load extensions into simulation executables,
+# so we need to ensure that all symbols in the executable are visible to
+# dynamically loaded libraries. However, not all linkers need or support
+# --export-dynamic.
+# Strategy: we'll compile the following program into a shared library:
+#      void function_from_main();
+#      void some_func() {func_from_main();}
+# Then we *independently* compile with the following program:
+#      #include <dlfcn.h>
+#      void func_from_main() {}
+#      int main() {return dlopen("libconftest_a.so",RTLD_NOW)==0;}
+# And we expect to be able to run the program successfully.
+#
+echo "$as_me:$LINENO: checking if --export-dynamic linker option is supported/needed" >&5
+echo $ECHO_N "checking if --export-dynamic linker option is supported/needed... $ECHO_C" >&6
+echo 'void func_from_main();' >conftest_a.cc
+echo 'void some_func() {func_from_main();}' >>conftest_a.cc
+echo '#include <dlfcn.h>' >conftest_m.cc
+echo '#include <stdio.h>' >>conftest_m.cc
+echo 'void func_from_main() {}' >>conftest_m.cc
+echo 'int main() {if (dlopen("./libconftest_a.so",RTLD_NOW)!=0) return 0; printf("%s\n",dlerror()); return 1;}' >>conftest_m.cc
+if $CXX -c conftest_a.cc >/dev/null 2>/dev/null && \
+   $CXX -c conftest_m.cc >/dev/null 2>/dev/null && \
+   $SHLIB_LD -o libconftest_a.so conftest_a.o >/dev/null 2>/dev/null; \
+then
+   silly_ok="no"
+   # 1st try.
+   if $CXX -o conftest conftest_m.o -ldl >/dev/null 2>/dev/null; then
+      if ./conftest >/dev/null 2>/dev/null; then
+         echo "$as_me:$LINENO: result: not needed" >&5
+echo "${ECHO_T}not needed" >&6
+         silly_ok="yes"
+      fi
+   fi
+   # 2nd try.
+   if test $silly_ok = "no" && \
+      $CXX -o conftest -Wl,--export-dynamic conftest_m.o -ldl >/dev/null 2>/dev/null; \
+   then
+      if ./conftest >/dev/null 2>/dev/null; then
+         echo "$as_me:$LINENO: result: supported and needed" >&5
+echo "${ECHO_T}supported and needed" >&6
+         LDFLAGS="$LDFLAGS -Wl,--export-dynamic"
+         silly_ok="yes"
+      fi
+   fi
+   # no solution found
+   if test $silly_ok = "no"; then
+      echo "$as_me:$LINENO: result: no solution found" >&5
+echo "${ECHO_T}no solution found" >&6
+      { echo "$as_me:$LINENO: WARNING: No way was detected to export symbols from executables to shared" >&5
+echo "$as_me: WARNING: No way was detected to export symbols from executables to shared" >&2;}
+      { echo "$as_me:$LINENO: WARNING: libraries. You probably will not be able to dynamically load" >&5
+echo "$as_me: WARNING: libraries. You probably will not be able to dynamically load" >&2;}
+      { echo "$as_me:$LINENO: WARNING: simple modules or other extensions written in C++ into simulation" >&5
+echo "$as_me: WARNING: simple modules or other extensions written in C++ into simulation" >&2;}
+      { echo "$as_me:$LINENO: WARNING: programs like INET." >&5
+echo "$as_me: WARNING: programs like INET." >&2;}
+   fi
+else
+   echo "$as_me:$LINENO: result: test failed" >&5
+echo "${ECHO_T}test failed" >&6
+fi
+rm -f conftest_a.* conftest_m.* libconftest_a.so conftest
+
+
+
+#----------------------
+# Test for "-z allextract" (Sun) or "--whole-archive" (GNU) linker option,
 #----------------------
 # Goal: to eliminate "silly linker problem", that is, to convince the linker
-# to include constructors of static C++ object in statically linked libraries.
+# to include constructors of static C++ objects in statically linked libraries.
 # To test, we'll compile the following code into a static library:
 #      #include <stdio.h>
 #      class A { public: A() {printf("=WORKS=\n");} };
@@ -2775,7 +2844,7 @@ else
    echo "$as_me:$LINENO: result: test failed" >&5
 echo "${ECHO_T}test failed" >&6
 fi
-rm -f conftest_a.* conftest_m.* libconftest_a.a
+rm -f conftest_a.* conftest_m.* libconftest_a.a conftest
 
 
 #----------------------
