*** empty log message ***

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -271,7 +271,7 @@ PACKAGE_STRING=
 PACKAGE_BUGREPORT=
 
 ac_unique_file="include/omnetpp.h"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX YACC LEX LEXLIB LEX_OUTPUT_ROOT RANLIB ac_ct_RANLIB DOXYGEN PERL XSLTPROC GHOSTSCRIPT CONVERT DOT GIFTRANS WISH CXXCPP OMNETPP_VERSION OMNETPP_BIN_DIR OMNETPP_INCL_DIR OMNETPP_LIB_DIR OMNETPP_BITMAP_PATH OMNETPP_SRC_DIR OMNETPP_UTILS_DIR OMNETPP_DOC_DIR OMNETPP_SAMPLES_DIR OMNETPP_TUTORIAL_DIR OMNETPP_TEST_DIR MYPWD NEDC MSGC NEDTOOL GNED NEDCFLAGS AS AR SHLIB_LD MAKEDEPEND A_LIB_SUFFIX SO_LIB_SUFFIX LIB_SUFFIX EXE_SUFFIX HAVE_DLOPEN TK_CFLAGS TK_LIBS HAVE_BLT BLT_LIBS HAVE_MPI MPI_CFLAGS MPI_LIBS SYS_LIBS XMLPARSER XML_CFLAGS XML_LIBS AKAROA_CFLAGS AKAROA_LIBS TKENV_IF_POSSIBLE GNED_IF_POSSIBLE SCALARS_IF_POSSIBLE PLOVE_IF_POSSIBLE TKENV_EMBED_SUFFIX GNED_EMBED_SUFFIX SCALARS_EMBED_SUFFIX PLOVE_EMBED_SUFFIX OMNETPP_TKENV_DIR OMNETPP_GNED_DIR OMNETPP_SCALARS_DIR OMNETPP_PLOVE_DIR WITH_NETBUILDER WITH_PARSIM LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX YACC LEX LEXLIB LEX_OUTPUT_ROOT RANLIB ac_ct_RANLIB DOXYGEN PERL XSLTPROC GHOSTSCRIPT CONVERT DOT GIFTRANS CXXCPP WISH OMNETPP_VERSION OMNETPP_BIN_DIR OMNETPP_INCL_DIR OMNETPP_LIB_DIR OMNETPP_BITMAP_PATH OMNETPP_SRC_DIR OMNETPP_UTILS_DIR OMNETPP_DOC_DIR OMNETPP_SAMPLES_DIR OMNETPP_TUTORIAL_DIR OMNETPP_TEST_DIR MYPWD NEDC MSGC NEDTOOL GNED NEDCFLAGS AS AR SHLIB_LD MAKEDEPEND A_LIB_SUFFIX SO_LIB_SUFFIX LIB_SUFFIX EXE_SUFFIX HAVE_DLOPEN TK_CFLAGS TK_LIBS HAVE_BLT BLT_LIBS HAVE_MPI MPI_CFLAGS MPI_LIBS SYS_LIBS XMLPARSER XML_CFLAGS XML_LIBS AKAROA_CFLAGS AKAROA_LIBS TKENV_IF_POSSIBLE GNED_IF_POSSIBLE SCALARS_IF_POSSIBLE PLOVE_IF_POSSIBLE TKENV_EMBED_SUFFIX GNED_EMBED_SUFFIX SCALARS_EMBED_SUFFIX PLOVE_EMBED_SUFFIX OMNETPP_TKENV_DIR OMNETPP_GNED_DIR OMNETPP_SCALARS_DIR OMNETPP_PLOVE_DIR WITH_NETBUILDER WITH_PARSIM LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -3801,56 +3801,6 @@ echo "$as_me: WARNING: no dlopen(): dynamic loading of libs not possible" >&2;}
 fi
 
 #----------------------
-# Check for wish.
-#----------------------
-for ac_prog in $WISH wish wish84 cygwish cygwish84
-do
-  # Extract the first word of "$ac_prog", so it can be a program name with args.
-set dummy $ac_prog; ac_word=$2
-echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_prog_WISH+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  if test -n "$WISH"; then
-  ac_cv_prog_WISH="$WISH" # Let the user override the test.
-else
-as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_prog_WISH="$ac_prog"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-
-fi
-fi
-WISH=$ac_cv_prog_WISH
-if test -n "$WISH"; then
-  echo "$as_me:$LINENO: result: $WISH" >&5
-echo "${ECHO_T}$WISH" >&6
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-
-  test -n "$WISH" && break
-done
-test -n "$WISH" || WISH="nope"
-
-if test "$WISH" = nope -a ! "$EMBED_TCL_CODE" = yes; then
-   OPP_PROBLEM_PACKAGES="$OPP_PROBLEM_PACKAGES wish"
-   { echo "$as_me:$LINENO: WARNING: cannot find wish, part of Tcl/Tk - Plove will not work" >&5
-echo "$as_me: WARNING: cannot find wish, part of Tcl/Tk - Plove will not work" >&2;}
-fi
-
-#----------------------
 # Check for Tcl/Tk.
 #----------------------
 
@@ -4724,9 +4674,57 @@ echo "$as_me: error: Tcl/Tk not found, needed for all GUI parts; version 8.4.0+ 
    { (exit 1); exit 1; }; }
     fi
 fi
-if echo 'catch {package require Tk 8.4; puts OK}; exit' | tclsh | grep OK >/dev/null; then :; else
-    { { echo "$as_me:$LINENO: error: Old Tcl/Tk version, 8.4.0+ required" >&5
-echo "$as_me: error: Old Tcl/Tk version, 8.4.0+ required" >&2;}
+
+# Check for wish.
+for ac_prog in $WISH wish wish85 wish84 cygwish cygwish85 cygwish84
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_WISH+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$WISH"; then
+  ac_cv_prog_WISH="$WISH" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_WISH="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+WISH=$ac_cv_prog_WISH
+if test -n "$WISH"; then
+  echo "$as_me:$LINENO: result: $WISH" >&5
+echo "${ECHO_T}$WISH" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$WISH" && break
+done
+test -n "$WISH" || WISH="nope"
+
+if test "$WISH" = nope; then
+   { { echo "$as_me:$LINENO: error: cannot find wish, part of Tcl/Tk -- maybe it is not in the PATH or has some exotic name (tested names were: wish wish85 wish84 cygwish cygwish85 cygwish84)" >&5
+echo "$as_me: error: cannot find wish, part of Tcl/Tk -- maybe it is not in the PATH or has some exotic name (tested names were: wish wish85 wish84 cygwish cygwish85 cygwish84)" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if echo 'catch {package require Tk 8.4; puts OK}; exit' | $WISH | grep OK >/dev/null; then :; else
+    { { echo "$as_me:$LINENO: error: wish command \"package require Tk 8.4\" failed: probably old Tcl/Tk version, version 8.4.0+ required" >&5
+echo "$as_me: error: wish command \"package require Tk 8.4\" failed: probably old Tcl/Tk version, version 8.4.0+ required" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -4787,10 +4785,10 @@ rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 
 if test $blt_ok = yes; then
     HAVE_BLT=yes
-    if echo 'catch {package require BLT 2.4; puts OK}; exit' | tclsh | grep OK >/dev/null; then :; else
+    if echo 'catch {package require BLT 2.4; puts OK}; exit' | $WISH | grep OK >/dev/null; then :; else
         OPP_PROBLEM_PACKAGES="$OPP_PROBLEM_PACKAGES BLT"
-        { echo "$as_me:$LINENO: WARNING: Tcl cannot load BLT, probably BLT not installed correctly." >&5
-echo "$as_me: WARNING: Tcl cannot load BLT, probably BLT not installed correctly." >&2;}
+        { echo "$as_me:$LINENO: WARNING: Tcl cannot load BLT (wish command \"package require BLT 2.4\" failed), probably BLT not installed correctly." >&5
+echo "$as_me: WARNING: Tcl cannot load BLT (wish command \"package require BLT 2.4\" failed), probably BLT not installed correctly." >&2;}
         { echo "$as_me:$LINENO: WARNING: Check your installation and try typing \"package require BLT 2.4\" on the wish prompt to verify!" >&5
 echo "$as_me: WARNING: Check your installation and try typing \"package require BLT 2.4\" on the wish prompt to verify!" >&2;}
     fi
@@ -6005,8 +6003,8 @@ s,@GHOSTSCRIPT@,$GHOSTSCRIPT,;t t
 s,@CONVERT@,$CONVERT,;t t
 s,@DOT@,$DOT,;t t
 s,@GIFTRANS@,$GIFTRANS,;t t
-s,@WISH@,$WISH,;t t
 s,@CXXCPP@,$CXXCPP,;t t
+s,@WISH@,$WISH,;t t
 s,@OMNETPP_VERSION@,$OMNETPP_VERSION,;t t
 s,@OMNETPP_BIN_DIR@,$OMNETPP_BIN_DIR,;t t
 s,@OMNETPP_INCL_DIR@,$OMNETPP_INCL_DIR,;t t
