*** empty log message ***

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -271,7 +271,7 @@ PACKAGE_STRING=
 PACKAGE_BUGREPORT=
 
 ac_unique_file="include/omnetpp.h"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX YACC LEX LEXLIB LEX_OUTPUT_ROOT RANLIB ac_ct_RANLIB DOXYGEN PERL XSLTPROC CONVERT GHOSTSCRIPT DOT GIFTRANS WISH CXXCPP OMNETPP_VERSION OMNETPP_BIN_DIR OMNETPP_INCL_DIR OMNETPP_LIB_DIR OMNETPP_BITMAP_PATH OMNETPP_SRC_DIR OMNETPP_UTILS_DIR OMNETPP_DOC_DIR OMNETPP_SAMPLES_DIR OMNETPP_TUTORIAL_DIR OMNETPP_TEST_DIR MYPWD NEDC MSGC NEDTOOL GNED NEDCFLAGS AS AR SHLIB_LD MAKEDEPEND A_LIB_SUFFIX SO_LIB_SUFFIX LIB_SUFFIX EXE_SUFFIX HAVE_DLOPEN TK_CFLAGS TK_LIBS HAVE_BLT BLT_LIBS HAVE_MPI MPI_CFLAGS MPI_LIBS SYS_LIBS XMLPARSER XML_CFLAGS XML_LIBS AKAROA_CFLAGS AKAROA_LIBS TKENV_IF_POSSIBLE GNED_IF_POSSIBLE SCALARS_IF_POSSIBLE PLOVE_IF_POSSIBLE TKENV_EMBED_SUFFIX GNED_EMBED_SUFFIX SCALARS_EMBED_SUFFIX PLOVE_EMBED_SUFFIX OMNETPP_TKENV_DIR OMNETPP_GNED_DIR OMNETPP_SCALARS_DIR OMNETPP_PLOVE_DIR WITH_NETBUILDER WITH_PARSIM LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX YACC LEX LEXLIB LEX_OUTPUT_ROOT RANLIB ac_ct_RANLIB DOXYGEN PERL XSLTPROC GHOSTSCRIPT CONVERT DOT GIFTRANS WISH CXXCPP OMNETPP_VERSION OMNETPP_BIN_DIR OMNETPP_INCL_DIR OMNETPP_LIB_DIR OMNETPP_BITMAP_PATH OMNETPP_SRC_DIR OMNETPP_UTILS_DIR OMNETPP_DOC_DIR OMNETPP_SAMPLES_DIR OMNETPP_TUTORIAL_DIR OMNETPP_TEST_DIR MYPWD NEDC MSGC NEDTOOL GNED NEDCFLAGS AS AR SHLIB_LD MAKEDEPEND A_LIB_SUFFIX SO_LIB_SUFFIX LIB_SUFFIX EXE_SUFFIX HAVE_DLOPEN TK_CFLAGS TK_LIBS HAVE_BLT BLT_LIBS HAVE_MPI MPI_CFLAGS MPI_LIBS SYS_LIBS XMLPARSER XML_CFLAGS XML_LIBS AKAROA_CFLAGS AKAROA_LIBS TKENV_IF_POSSIBLE GNED_IF_POSSIBLE SCALARS_IF_POSSIBLE PLOVE_IF_POSSIBLE TKENV_EMBED_SUFFIX GNED_EMBED_SUFFIX SCALARS_EMBED_SUFFIX PLOVE_EMBED_SUFFIX OMNETPP_TKENV_DIR OMNETPP_GNED_DIR OMNETPP_SCALARS_DIR OMNETPP_PLOVE_DIR WITH_NETBUILDER WITH_PARSIM LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -748,14 +748,14 @@ ac_env_XSLTPROC_set=${XSLTPROC+set}
 ac_env_XSLTPROC_value=$XSLTPROC
 ac_cv_env_XSLTPROC_set=${XSLTPROC+set}
 ac_cv_env_XSLTPROC_value=$XSLTPROC
-ac_env_CONVERT_set=${CONVERT+set}
-ac_env_CONVERT_value=$CONVERT
-ac_cv_env_CONVERT_set=${CONVERT+set}
-ac_cv_env_CONVERT_value=$CONVERT
 ac_env_GHOSTSCRIPT_set=${GHOSTSCRIPT+set}
 ac_env_GHOSTSCRIPT_value=$GHOSTSCRIPT
 ac_cv_env_GHOSTSCRIPT_set=${GHOSTSCRIPT+set}
 ac_cv_env_GHOSTSCRIPT_value=$GHOSTSCRIPT
+ac_env_CONVERT_set=${CONVERT+set}
+ac_env_CONVERT_value=$CONVERT
+ac_cv_env_CONVERT_set=${CONVERT+set}
+ac_cv_env_CONVERT_value=$CONVERT
 ac_env_DOT_set=${DOT+set}
 ac_env_DOT_value=$DOT
 ac_cv_env_DOT_set=${DOT+set}
@@ -860,9 +860,9 @@ Some influential environment variables:
   DOXYGEN     The Doxygen documentation tool
   PERL        The Perl interpreter
   XSLTPROC    A command line xslt processor
+  GHOSTSCRIPT Ghostscript is used for EPS-JPG conversion by opp_neddoc
   CONVERT     convert (ImageMagick) is used for EPS-JPG conversion by
               opp_neddoc
-  GHOSTSCRIPT Ghostscript is used for EPS-JPG conversion by opp_neddoc
   DOT         Graph drawing program from the Graphviz package
   GIFTRANS    Utility to make GIFs transparent
   CXXCPP      C++ preprocessor
@@ -2578,6 +2578,9 @@ case $host in
     ;;
 esac
 
+# We'll collect in this variable the components we've detected problems with
+OPP_PROBLEM_PACKAGES=
+
 #
 # Location of various components. Can be overridden in configure.user.
 #
@@ -2755,8 +2758,9 @@ done
 test -n "$YACC" || YACC="yacc"
 
 if test "$YACC" = "yacc"; then
-   { echo "$as_me:$LINENO: WARNING: neither bison nor byacc is found..." >&5
-echo "$as_me: WARNING: neither bison nor byacc is found..." >&2;}
+   { { echo "$as_me:$LINENO: error: Bison not found, needed to build OMNeT++ -- please install it!" >&5
+echo "$as_me: error: Bison not found, needed to build OMNeT++ -- please install it!" >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 for ac_prog in flex lex
@@ -3125,8 +3129,9 @@ fi
 
 
 if test "$DOXYGEN" = "not found"; then
-   { echo "$as_me:$LINENO: WARNING: doxygen is needed to create the OMNeT++ API reference." >&5
-echo "$as_me: WARNING: doxygen is needed to create the OMNeT++ API reference." >&2;}
+   OPP_PROBLEM_PACKAGES="$OPP_PROBLEM_PACKAGES doxygen"
+   { echo "$as_me:$LINENO: WARNING: doxygen not found -- it is needed to create the OMNeT++ API reference and also useful with opp_neddoc." >&5
+echo "$as_me: WARNING: doxygen not found -- it is needed to create the OMNeT++ API reference and also useful with opp_neddoc." >&2;}
    { echo "$as_me:$LINENO: WARNING: It is available from http://www.doxygen.org/" >&5
 echo "$as_me: WARNING: It is available from http://www.doxygen.org/" >&2;}
 fi
@@ -3210,48 +3215,11 @@ fi
 
 
 if test "$XSLTPROC" = "not found"; then
-   { echo "$as_me:$LINENO: WARNING: xsltproc is needed for opp_neddoc." >&5
-echo "$as_me: WARNING: xsltproc is needed for opp_neddoc." >&2;}
+   OPP_PROBLEM_PACKAGES="$OPP_PROBLEM_PACKAGES xsltproc"
+   { echo "$as_me:$LINENO: WARNING: xsltproc from the libxml/libxslt packages not found -- it is needed by opp_neddoc." >&5
+echo "$as_me: WARNING: xsltproc from the libxml/libxslt packages not found -- it is needed by opp_neddoc." >&2;}
    { echo "$as_me:$LINENO: WARNING: You can get it from http://xmlsoft.org/XSLT/" >&5
 echo "$as_me: WARNING: You can get it from http://xmlsoft.org/XSLT/" >&2;}
-fi
-
-
-# "convert" from ImageMagick
-
-# Extract the first word of "convert", so it can be a program name with args.
-set dummy convert; ac_word=$2
-echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_prog_CONVERT+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  if test -n "$CONVERT"; then
-  ac_cv_prog_CONVERT="$CONVERT" # Let the user override the test.
-else
-as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_prog_CONVERT="convert"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-
-fi
-fi
-CONVERT=$ac_cv_prog_CONVERT
-if test -n "$CONVERT"; then
-  echo "$as_me:$LINENO: result: $CONVERT" >&5
-echo "${ECHO_T}$CONVERT" >&6
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
 fi
 
 
@@ -3294,13 +3262,53 @@ fi
 
 
 if test "$GHOSTSCRIPT" = ""; then
-   { echo "$as_me:$LINENO: WARNING: Ghostscript is needed by opp_neddoc to create diagrams." >&5
-echo "$as_me: WARNING: Ghostscript is needed by opp_neddoc to create diagrams." >&2;}
+   OPP_PROBLEM_PACKAGES="$OPP_PROBLEM_PACKAGES Ghostscript"
+   { echo "$as_me:$LINENO: WARNING: Ghostscript not found -- it is needed by opp_neddoc to create diagrams." >&5
+echo "$as_me: WARNING: Ghostscript not found -- it is needed by opp_neddoc to create diagrams." >&2;}
+fi
+
+# "convert" from ImageMagick
+
+# Extract the first word of "convert", so it can be a program name with args.
+set dummy convert; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_CONVERT+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-   if test "$CONVERT" = ""; then
-      { echo "$as_me:$LINENO: WARNING: ImageMagick not found -- opp_neddoc may export broken network diagrams due to a Ghostscript problem." >&5
-echo "$as_me: WARNING: ImageMagick not found -- opp_neddoc may export broken network diagrams due to a Ghostscript problem." >&2;}
-   fi
+  if test -n "$CONVERT"; then
+  ac_cv_prog_CONVERT="$CONVERT" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_CONVERT="convert"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+CONVERT=$ac_cv_prog_CONVERT
+if test -n "$CONVERT"; then
+  echo "$as_me:$LINENO: result: $CONVERT" >&5
+echo "${ECHO_T}$CONVERT" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+if test "$CONVERT" = ""; then
+   OPP_PROBLEM_PACKAGES="$OPP_PROBLEM_PACKAGES ImageMagick"
+   { echo "$as_me:$LINENO: WARNING: convert program from the ImageMagick package not found -- opp_neddoc may export broken network diagrams due to a Ghostscript problem." >&5
+echo "$as_me: WARNING: convert program from the ImageMagick package not found -- opp_neddoc may export broken network diagrams due to a Ghostscript problem." >&2;}
 fi
 
 # "dot" from Graphviz
@@ -3342,8 +3350,9 @@ fi
 
 
 if test "$DOT" = ""; then
-   { echo "$as_me:$LINENO: WARNING: The dot program from Graphviz is needed by opp_neddoc to generate diagrams." >&5
-echo "$as_me: WARNING: The dot program from Graphviz is needed by opp_neddoc to generate diagrams." >&2;}
+   OPP_PROBLEM_PACKAGES="$OPP_PROBLEM_PACKAGES Graphviz"
+   { echo "$as_me:$LINENO: WARNING: dot program from Graphviz not found -- it is needed by opp_neddoc to generate diagrams." >&5
+echo "$as_me: WARNING: dot program from Graphviz not found -- it is needed by opp_neddoc to generate diagrams." >&2;}
 fi
 
 # giftrans
@@ -3385,8 +3394,9 @@ fi
 
 
 if test "$GIFTRANS" = ""; then
-   { echo "$as_me:$LINENO: WARNING: giftrans is used by opp_neddoc" >&5
-echo "$as_me: WARNING: giftrans is used by opp_neddoc" >&2;}
+   OPP_PROBLEM_PACKAGES="$OPP_PROBLEM_PACKAGES giftrans"
+   { echo "$as_me:$LINENO: WARNING: giftrans not found -- opp_neddoc needs it to make the background of diagrams transparent." >&5
+echo "$as_me: WARNING: giftrans not found -- opp_neddoc needs it to make the background of diagrams transparent." >&2;}
 fi
 
 #----------------------
@@ -3835,6 +3845,7 @@ done
 test -n "$WISH" || WISH="nope"
 
 if test "$WISH" = nope -a ! "$EMBED_TCL_CODE" = yes; then
+   OPP_PROBLEM_PACKAGES="$OPP_PROBLEM_PACKAGES wish"
    { echo "$as_me:$LINENO: WARNING: cannot find wish, part of Tcl/Tk - Plove will not work" >&5
 echo "$as_me: WARNING: cannot find wish, part of Tcl/Tk - Plove will not work" >&2;}
 fi
@@ -4708,10 +4719,15 @@ echo "$as_me: error: cannot build Tcl/Tk apps, probably due to misconfigured or 
    { (exit 1); exit 1; }; }
         fi
     else
-        { { echo "$as_me:$LINENO: error: Tcl/Tk not found, needed for all GUI parts; version 8.4.0+ needed" >&5
-echo "$as_me: error: Tcl/Tk not found, needed for all GUI parts; version 8.4.0+ needed" >&2;}
+        { { echo "$as_me:$LINENO: error: Tcl/Tk not found, needed for all GUI parts; version 8.4.0+ required" >&5
+echo "$as_me: error: Tcl/Tk not found, needed for all GUI parts; version 8.4.0+ required" >&2;}
    { (exit 1); exit 1; }; }
     fi
+fi
+if echo 'catch {package require Tk 8.4; puts OK}; exit' | tclsh | grep OK >/dev/null; then :; else
+    { { echo "$as_me:$LINENO: error: Old Tcl/Tk version, 8.4.0+ required" >&5
+echo "$as_me: error: Old Tcl/Tk version, 8.4.0+ required" >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 #----------------------
@@ -4771,7 +4787,15 @@ rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 
 if test $blt_ok = yes; then
     HAVE_BLT=yes
+    if echo 'catch {package require BLT 2.8; puts OK}; exit' | tclsh | grep OK >/dev/null; then :; else
+        OPP_PROBLEM_PACKAGES="$OPP_PROBLEM_PACKAGES BLT"
+        { echo "$as_me:$LINENO: WARNING: Tcl cannot load BLT, probably BLT not installed correctly." >&5
+echo "$as_me: WARNING: Tcl cannot load BLT, probably BLT not installed correctly." >&2;}
+        { echo "$as_me:$LINENO: WARNING: Check your installation and try typing \"package require BLT 2.4\" on the wish prompt to verify!" >&5
+echo "$as_me: WARNING: Check your installation and try typing \"package require BLT 2.4\" on the wish prompt to verify!" >&2;}
+    fi
 else
+    OPP_PROBLEM_PACKAGES="$OPP_PROBLEM_PACKAGES BLT"
     { echo "$as_me:$LINENO: WARNING: no BLT: Plove and Scalars will not build or work" >&5
 echo "$as_me: WARNING: no BLT: Plove and Scalars will not build or work" >&2;}
     HAVE_BLT=no
@@ -5070,6 +5094,7 @@ echo "$as_me: WARNING: DTD validation is not supported with Expat, only with Lib
    XML_LIBS=$EXPAT_LIBS
 else
    XMLPARSER=none
+   OPP_PROBLEM_PACKAGES="$OPP_PROBLEM_PACKAGES (no XML parser)"
    { echo "$as_me:$LINENO: WARNING: No suitable XML parser found: no support for XML input" >&5
 echo "$as_me: WARNING: No suitable XML parser found: no support for XML input" >&2;}
 fi
@@ -5976,8 +6001,8 @@ s,@ac_ct_RANLIB@,$ac_ct_RANLIB,;t t
 s,@DOXYGEN@,$DOXYGEN,;t t
 s,@PERL@,$PERL,;t t
 s,@XSLTPROC@,$XSLTPROC,;t t
-s,@CONVERT@,$CONVERT,;t t
 s,@GHOSTSCRIPT@,$GHOSTSCRIPT,;t t
+s,@CONVERT@,$CONVERT,;t t
 s,@DOT@,$DOT,;t t
 s,@GIFTRANS@,$GIFTRANS,;t t
 s,@WISH@,$WISH,;t t
@@ -6272,6 +6297,26 @@ chmod +x src/utils/opp_makemake
 chmod +x src/utils/opp_test
 chmod +x src/utils/opp_makedep
 chmod +x src/utils/opp_neddoc
+
+
+#----------------------
+# Check $OPP_PROBLEM_PACKAGES
+#----------------------
+
+if test "$OPP_PROBLEM_PACKAGES" != ""; then
+      cat 1>&2 << EOT
+
+WARNING: The configuration script found problems with the following packages:
+
+  $OPP_PROBLEM_PACKAGES
+
+Scroll up to see the warning messages (use shift+PgUp key). While you can
+still use OMNeT++ in the current configuration, be aware that certain
+functionality may be degraded or unavailable.
+
+EOT
+fi
+
 
 #----------------------
 # Check if the path contains omnetpp/bin (it should)
