'tcl/tk not found' errmsg refined

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1339,6 +1339,7 @@ host_os=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
 
 
 # figure out here if we have gcc or not -- we'll need it soon
+#FIXME: skip if CC var already exists
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -4108,115 +4109,6 @@ fi
        fi
     fi
 fi
-if test $tcltk_ok = no -a "$cygwin" = yes; then
-    # in Cygwin, we try 8.4, 8.3 and 8.0:
-
-   save_CXXFLAGS=$CXXFLAGS
-   save_LIBS=$LIBS
-
-   CXXFLAGS="$opp_x11inc $TK_CFLAGS"
-   LIBS="$opp_x11lib -lcygtk84 -lcygtcl84"
-
-   echo "$as_me:$LINENO: checking for Tcl/Tk with CFLAGS=\"$opp_x11inc $TK_CFLAGS\" LIBS=\"$opp_x11lib -lcygtk84 -lcygtcl84\"" >&5
-echo $ECHO_N "checking for Tcl/Tk with CFLAGS=\"$opp_x11inc $TK_CFLAGS\" LIBS=\"$opp_x11lib -lcygtk84 -lcygtcl84\"... $ECHO_C" >&6
-
-   cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-#include <tk.h>
-int
-main ()
-{
-Tk_MainLoop();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6; tcltk_ok=yes; TK_LIBS="$opp_x11lib -lcygtk84 -lcygtcl84"
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; tcltk_ok=no;
-fi
-rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
-
-   CXXFLAGS=$save_CXXFLAGS
-   LIBS=$save_LIBS
-
-    if test $tcltk_ok = no; then
-
-   save_CXXFLAGS=$CXXFLAGS
-   save_LIBS=$LIBS
-
-   CXXFLAGS="$opp_x11inc $TK_CFLAGS"
-   LIBS="$opp_x11lib -lcygtk83 -lcygtcl83"
-
-   echo "$as_me:$LINENO: checking for Tcl/Tk with CFLAGS=\"$opp_x11inc $TK_CFLAGS\" LIBS=\"$opp_x11lib -lcygtk83 -lcygtcl83\"" >&5
-echo $ECHO_N "checking for Tcl/Tk with CFLAGS=\"$opp_x11inc $TK_CFLAGS\" LIBS=\"$opp_x11lib -lcygtk83 -lcygtcl83\"... $ECHO_C" >&6
-
-   cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-#include <tk.h>
-int
-main ()
-{
-Tk_MainLoop();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6; tcltk_ok=yes; TK_LIBS="$opp_x11lib -lcygtk83 -lcygtcl83"
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; tcltk_ok=no;
-fi
-rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
-
-   CXXFLAGS=$save_CXXFLAGS
-   LIBS=$save_LIBS
-
-    fi
-fi
 if test $tcltk_ok = no; then
 
    save_CXXFLAGS=$CXXFLAGS
@@ -4325,6 +4217,60 @@ rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
    LIBS=$save_LIBS
 
 fi
+if test $tcltk_ok = no -a "$cygwin" = yes; then
+
+   save_CXXFLAGS=$CXXFLAGS
+   save_LIBS=$LIBS
+
+   CXXFLAGS="$opp_x11inc $TK_CFLAGS"
+   LIBS="$opp_x11lib -lcygtk84 -lcygtcl84"
+
+   echo "$as_me:$LINENO: checking for Tcl/Tk with CFLAGS=\"$opp_x11inc $TK_CFLAGS\" LIBS=\"$opp_x11lib -lcygtk84 -lcygtcl84\"" >&5
+echo $ECHO_N "checking for Tcl/Tk with CFLAGS=\"$opp_x11inc $TK_CFLAGS\" LIBS=\"$opp_x11lib -lcygtk84 -lcygtcl84\"... $ECHO_C" >&6
+
+   cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <tk.h>
+int
+main ()
+{
+Tk_MainLoop();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; tcltk_ok=yes; TK_LIBS="$opp_x11lib -lcygtk84 -lcygtcl84"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; tcltk_ok=no;
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+
+   CXXFLAGS=$save_CXXFLAGS
+   LIBS=$save_LIBS
+
+fi
 if test $tcltk_ok = no; then
 
    save_CXXFLAGS=$CXXFLAGS
@@ -4420,6 +4366,60 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   (exit $ac_status); }; }; then
   echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; tcltk_ok=yes; TK_LIBS="$opp_x11lib -ltk8.3 -ltcl8.3"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; tcltk_ok=no;
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+
+   CXXFLAGS=$save_CXXFLAGS
+   LIBS=$save_LIBS
+
+fi
+if test $tcltk_ok = no -a "$cygwin" = yes; then
+
+   save_CXXFLAGS=$CXXFLAGS
+   save_LIBS=$LIBS
+
+   CXXFLAGS="$opp_x11inc $TK_CFLAGS"
+   LIBS="$opp_x11lib -lcygtk83 -lcygtcl83"
+
+   echo "$as_me:$LINENO: checking for Tcl/Tk with CFLAGS=\"$opp_x11inc $TK_CFLAGS\" LIBS=\"$opp_x11lib -lcygtk83 -lcygtcl83\"" >&5
+echo $ECHO_N "checking for Tcl/Tk with CFLAGS=\"$opp_x11inc $TK_CFLAGS\" LIBS=\"$opp_x11lib -lcygtk83 -lcygtcl83\"... $ECHO_C" >&6
+
+   cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <tk.h>
+int
+main ()
+{
+Tk_MainLoop();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; tcltk_ok=yes; TK_LIBS="$opp_x11lib -lcygtk83 -lcygtcl83"
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
@@ -4542,16 +4542,28 @@ rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 
 fi
 if test $tcltk_ok = yes; then
-   TKENV_IF_POSSIBLE=tkenv
-   GNED_IF_POSSIBLE=gned
-   PLOVE_IF_POSSIBLE=plove
+    TKENV_IF_POSSIBLE=tkenv
+    GNED_IF_POSSIBLE=gned
+    PLOVE_IF_POSSIBLE=plove
 else
-   TKENV_IF_POSSIBLE=missing-library
-   GNED_IF_POSSIBLE=missing-library
-   PLOVE_IF_POSSIBLE=missing-library
-   { { echo "$as_me:$LINENO: error: Tcl/Tk not found, needed for all GUI parts; version 8.2+ needed" >&5
+    TKENV_IF_POSSIBLE=missing-library
+    GNED_IF_POSSIBLE=missing-library
+    PLOVE_IF_POSSIBLE=missing-library
+    if test "$no_x" = "yes"; then
+        if test "$cygwin" = yes; then
+            { { echo "$as_me:$LINENO: error: cannot build Tcl/Tk apps, probably due to missing X11 headers -- try installing the XFree86 packages or get the X headers from the OMNeT++ site" >&5
+echo "$as_me: error: cannot build Tcl/Tk apps, probably due to missing X11 headers -- try installing the XFree86 packages or get the X headers from the OMNeT++ site" >&2;}
+   { (exit 1); exit 1; }; }
+        else
+            { { echo "$as_me:$LINENO: error: cannot build Tcl/Tk apps, probably due to misconfigured or missing X11 headers or libs" >&5
+echo "$as_me: error: cannot build Tcl/Tk apps, probably due to misconfigured or missing X11 headers or libs" >&2;}
+   { (exit 1); exit 1; }; }
+        fi
+    else
+        { { echo "$as_me:$LINENO: error: Tcl/Tk not found, needed for all GUI parts; version 8.2+ needed" >&5
 echo "$as_me: error: Tcl/Tk not found, needed for all GUI parts; version 8.2+ needed" >&2;}
    { (exit 1); exit 1; }; }
+    fi
 fi
 
 
