makemake renamed to opp_makemake

diff --git a/src/utils/makemake.in b/src/utils/makemake.in
--- a/src/utils/makemake.in
+++ b/src/utils/makemake.in
@@ -1,5 +1,5 @@
 #!/bin/sh
-# makemake (formerly jar_mkmk)
+# opp_makemake (formerly jar_mkmk)
 #
 #  Creates a makefile for a given OMNeT++ model.
 #  Assumes that .ned, .cc and .h files are in one directory.
@@ -30,9 +30,9 @@ while [ ! $# = 0 ] ; do
 
         -h | --help)
         cat <<EOT
-makemake: write OMNeT++ Makefile based on source files in current directory
+opp_makemake: write OMNeT++ Makefile based on source files in current directory
 
-makemake [-h] [-f] [-m] [-o make-target] [-t exe|so|o] [-u user-interface] [-p]
+opp_makemake [-h] [-f] [-m] [-o make-target] [-t exe|so|o] [-u user-interface] [-p]
          [-Idir] [-llibrary] [-i makefile-fragment-file]
          [directories, library and object files]...
     -h, --help            This help text
@@ -55,8 +55,8 @@ makemake [-h] [-f] [-m] [-o make-target] [-t exe|so|o] [-u user-interface] [-p]
     library or object     Link with that file
 
 With the -n and -s options, -u, -p and -l have no effect.
-If you have a source tree instead of a single directory, run makemake -n
-in the subdirs and then makemake dir1 dir2 etc. in your top-level directory.
+If you have a source tree instead of a single directory, run opp_makemake -n
+in the subdirs and then opp_makemake dir1 dir2 etc. in your top-level directory.
 The -i option is useful if a source file (.ned or .cc) is to be generated
 from other files.
 EOT
@@ -91,7 +91,7 @@ EOT
             CMDENV | TKENV)
             ;;
             *)
-            echo "makemake: -u: valid user interface names are Cmdenv or Tkenv" 1>&2
+            echo "opp_makemake: -u: valid user interface names are Cmdenv or Tkenv" 1>&2
             exit
             ;;
         esac
@@ -119,7 +119,7 @@ EOT
             dirs="$dirs $1"
         else
             if [ ! -f $1 ]; then
-                echo "makemake: $1 is neither an existing file/dir nor a valid option" 1>&2
+                echo "opp_makemake: $1 is neither an existing file/dir nor a valid option" 1>&2
                 exit
             fi
             xobjs="$xobjs $1"
@@ -138,12 +138,12 @@ fi
 
 if [ -f $outputfile ]; then
     if [ ! -s $outputfile ]; then
-        echo "makemake: synopsis changed (no longer needs >$outputfile), type makemake -h" 1>&2
+        echo "opp_makemake: synopsis changed (no longer needs >$outputfile), type opp_makemake -h" 1>&2
         rm $outputfile
         exit
     fi
     if [ ! "$force" = "y" ]; then
-        echo "makemake: use -f to force overwriting existing $outputfile" 1>&2
+        echo "opp_makemake: use -f to force overwriting existing $outputfile" 1>&2
         exit
     fi
 fi
@@ -154,12 +154,12 @@ for i in $dirs; do
     if (cd $i && make); then
         o=`echo $i/*.o`
         if [ "$o" = "$i/*.o" ]; then
-            echo "makemake: warning: no object files in $i" 1>&2
+            echo "opp_makemake: warning: no object files in $i" 1>&2
         else
             sobjs="$sobjs $o"
         fi
     else
-        echo "makemake: make in $i failed, exiting" 1>&2
+        echo "opp_makemake: make in $i failed, exiting" 1>&2
         exit
     fi
 done
@@ -176,7 +176,7 @@ cat <<EOT
 #  Makefile for $outfile
 #
 #  ** This file was automatically generated by the command:
-#  makemake $args
+#  opp_makemake $args
 #
 EOT
 
@@ -382,10 +382,10 @@ depend:
 	makedepend -Y \$(INCLUDE_PATH) -fMakefile.in -- *.cc
 
 re-makemake:
-	makemake -f $args1  #recreate Makefile
+	opp_makemake -f $args1  #recreate Makefile
 
 re-makemake-m:
-	makemake -f -m $args1  #recreate Makefile.in
+	opp_makemake -f -m $args1  #recreate Makefile.in
 
 # DO NOT DELETE THIS LINE -- make depend depends on it.
 
