*** empty log message ***

diff --git a/src/utils/opp_neddoc.in b/src/utils/opp_neddoc.in
--- a/src/utils/opp_neddoc.in
+++ b/src/utils/opp_neddoc.in
@@ -1,179 +1,405 @@
-#! /bin/sh
-PS2GIF=@PS2GIF@
-GIFTRANS=@GIFTRANS@
-DOT=@DOT@
-NEDDOC_XSL=`dirname $0`/neddoc.xsl
-NEDDOC_PL=`dirname $0`/neddocproc.pl
-TMPFILE=/tmp/opp_neddoc.tmp.$$
+eval '(exit $?0)' && eval 'exec perl -S $0 ${1+"$@"}' && eval 'exec perl -S $0 $argv:q'
+  if 0;
 
-# process command-line options
-outdir=html
-screenshots=yes
-unassignedpars=yes
-doxytagfile=
-doxyhtmldir="../api-doc/html"
+#!perl
+#line 6
 
-if [ -n $DOT ]; then
-    have_dot=yes
-fi    
-while [ $# -gt 0 ]; do
-    case "$1" in
-    -o)       shift; outdir=$1 ;;
-    -a)       all_files=y ;;
-    --all)    all_files=y ;;
-    -d)       shift; doxyhtmldir=$1 ;;
-    --doxyhtmldir)  shift; doxyhtmldir=$1 ;;
-    -t)       shift; doxytagfile=$1 ;;
-    --doxytagfile)  shift; doxytagfile=$1 ;;
-    -n)       screenshots=no ;;
-    --no-figures)  screenshots=no ;;
-    -p)       unassignedpars=no ;;
-    --no-unassigned-pars)  unassignedpars=no ;;
-    -x)       have_dot=no ;;
-    --no-diagrams)  have_dot=no ;;
-    -h)       do_help=y ;;
-    --help)   do_help=y ;;
-    -*)       echo "opp_neddoc: ${1}: invalid option, try -h for help" >&2
-              exit 2 ;;
-    *)        break ;;
-    esac
-    shift
-done
+#--------------------------------------------------
+# Following lines are configured by the Makefile:
+$NEDTOOL = "@NEDTOOL@";
+$XSLTPROC = "@XSLTPROC@";
+$GNED = "@GNED@";
+$GHOSTSCRIPT = "@GHOSTSCRIPT@";
+$GIFTRANS = "@GIFTRANS@";
+$DOT = "@DOT@";
+$PERL = "@PERL@";
+#--------------------------------------------------
 
-if [ -n "$do_help" ]; then
-    echo "opp_neddoc - NED and MSG documentation tool, part of OMNeT++"
-    echo "(c) 2003 Andras Varga"
-    echo ""
-    if [ ! -n "$PS2GIF" ]; then
-        echo "(Note: generating figures not possible -- ImageMagick's 'convert' is not present.)"
-        echo ""
-    fi
-    echo "Usage: opp_neddoc [-o <dir>] [-n] [-a] files-or-directories ..."
-    echo " -a, --all    process all *.ned and *.msg files recursively"
-    echo "              ('opp_neddoc -a' is equivalent to 'opp_neddoc .')"
-    echo " -o <dir>     output directory, defaults to ./html"
-    echo " -t <filename>, --doxytagfile <filename>"
-    echo "              turn on generating hyperlinks to Doxygen documentation;"
-    echo "              <filename> specifies name of XML tag file generated by Doxygen"
-    echo " -d <dir>, --doxyhtmldir <dir>"
-    echo "              directory of Doxygen-generated HTML files, relative to the "
-    echo "              opp_neddoc output directory (-o option). -t option must also be"
-    echo "              present to turn on linking to Doxygen. Default: ../api-doc/html"
-    echo " -n, --no-figures"
-    echo "              do not generate diagrams"
-    echo " -p, --no-unassigned-pars"
-    echo "              do not document unassigned parameters"
-    echo " -x, --no-diagrams"
-    echo "              do not generate usage and inheritance diagrams"
-    echo " -h, --help   displays this help text"
-    echo "Files specified as arguments are parsed and documented. If directories"
-    echo "are specified, all *.ned and *.msg files in them are documented."
-    echo ""
-    exit
-fi
+# OS check
+use Config;
 
-cleanup()
+#if ($Config{'archname'} =~ /cygwin/i || $ENV{TERM} =~ /cygwin/i)
+if ($Config{'archname'} =~ /cygwin/i)
 {
-    rm $TMPFILE
+    # forget cygwin: its /cygdrive/c/.. style paths are not understood by any normal program...
+    error("the Cygwin environment and Cygwin's perl are not supported, please\n".
+          "run this program from the Windows command prompt, or install MinGW instead of\n".
+          "Cygwin!");
 }
 
-trap cleanup HUP INT QUIT TERM
+$isWindows = ($ENV{OS} =~ /windows/i) ? 1 : 0;
 
-if [ ! -d $outdir ]; then
-    mkdir $outdir || exit 1
-fi
-rm -f $outdir/* || exit 1
+if ($isWindows && $ENV{OS} ne "Windows_NT")
+{
+    error("this program can only be used on Windows NT/2000/XP, but your OS environment variable says '$ENV{OS}'\n");
+}
 
-echo collecting files...
-if [ -n "$all_files" ]; then
-    files=`find . -name '*.ned' -o -name '*.msg'` || exit 1
+use Cwd;
+
+$progdir = directoryof($0);
+
+# assume the stylesheet and the postprocessor are in the same directory as we
+$NEDDOC_XSL = "$progdir/neddoc.xsl";
+$NEDDOC_PL = "$progdir/neddocproc.pl";
+
+# process command-line options
+$outdir = "html";
+$doxytagfile = "";
+$doxyhtmldir = "../api-doc/html";
+$screenshots = 1;
+$unassignedpars = 1;
+$all_files = 0;
+$verbose = 1;
+$debug = 0;
+
+if ($DOT ne "")
+{
+    $have_dot = 1;
+}
+
+# process arg vector
+while (@ARGV)
+{
+    $arg = $ARGV[0];
+    if ($arg eq '-o')
+    {
+       shift @ARGV;
+       $outdir = tobackslash($ARGV[0]);
+    }
+    elsif ($arg eq '-a' || $arg eq '--all')
+    {
+       $all_files = 1;
+    }
+    elsif ($arg eq '-d' || $arg eq '--doxyhtmldir')
+    {
+       shift @ARGV;
+       $doxyhtmldir = tobackslash($ARGV[0]);
+    }
+    elsif ($arg eq '-t' || $arg eq '--doxytagfile')
+    {
+       shift @ARGV;
+       $doxytagfile = tobackslash($ARGV[0]);
+    }
+    elsif ($arg eq '-n' || $arg eq '--no-figures')
+    {
+       $screenshots = 0;
+    }
+    elsif ($arg eq '-p' || $arg eq '--no-unassigned-pars')
+    {
+       $unassignedpars = 0;
+    }
+    elsif ($arg eq '-x' || $arg eq '--no-diagrams')
+    {
+       $have_dot = 1;
+    }
+    elsif ($arg eq '-g' || $arg eq '--debug')
+    {
+       $debug = 1;
+    }
+    elsif ($arg eq '-s' || $arg eq '--silent')
+    {
+       $verbose = 0;
+    }
+    elsif ($arg eq '-h' || $arg eq '--help')
+    {
+       $do_help = 1;
+    }
+    elsif ($arg =~ /^-/)
+    {
+       print STDERR "opp_neddoc: $arg: invalid option, try -h for help\n";
+       exit(2);
+    }
+    else
+    {
+       last;
+    }
+    shift @ARGV;
+}
+
+if ($do_help)
+{
+    print "opp_neddoc - NED and MSG documentation tool, part of OMNeT++\n";
+    print "(c) 2003 Andras Varga\n";
+    print "\n";
+    if ($GHOSTSCRIPT eq "")
+    {
+        print "Note: cannot generate figures because Ghostscript is not installed.\n";
+        print "\n";
+    }
+    if ($DOT eq "")
+    {
+        print "Note: cannot generate usage diagrams because Graphviz is not installed.\n";
+        print "\n";
+    }
+    print "Usage: opp_neddoc [-o <dir>] [-n] [-a] files-or-directories ...\n";
+    print " -s, --silent do not print what it is doing\n";
+    print " -g, --debug  print invocations of external programs and other info\n";
+    print " -a, --all    process all *.ned and *.msg files recursively\n";
+    print "              ('opp_neddoc -a' is equivalent to 'opp_neddoc .')\n";
+    print " -o <dir>     output directory, defaults to ./html\n";
+    print " -t <filename>, --doxytagfile <filename>\n";
+    print "              turn on generating hyperlinks to Doxygen documentation;\n";
+    print "              <filename> specifies name of XML tag file generated by Doxygen\n";
+    print " -d <dir>, --doxyhtmldir <dir>\n";
+    print "              directory of Doxygen-generated HTML files, relative to the \n";
+    print "              opp_neddoc output directory (-o option). -t option must also be\n";
+    print "              present to turn on linking to Doxygen. Default: ../api-doc/html\n";
+    print " -n, --no-figures\n";
+    print "              do not generate diagrams\n";
+    print " -p, --no-unassigned-pars\n";
+    print "              do not document unassigned parameters\n";
+    print " -x, --no-diagrams\n";
+    print "              do not generate usage and inheritance diagrams\n";
+    print " -h, --help   displays this help text\n";
+    print "Files specified as arguments are parsed and documented. If directories\n";
+    print "are specified, all *.ned and *.msg files in them are documented.\n";
+    print "\n";
+    exit(0);
+}
+
+# print platform
+print (($isWindows ? "windows" : "unix"), " environment detected\n") if $debug;
+
+# we need backslashes in file names
+$NEDTOOL = tobackslash($NEDTOOL);
+$XSLTPROC = tobackslash($XSLTPROC);
+$GNED = tobackslash($GNED);
+$GHOSTSCRIPT = tobackslash($GHOSTSCRIPT);
+$GIFTRANS = tobackslash($GIFTRANS);
+$DOT = tobackslash($DOT);
+$PERL = tobackslash($PERL);
+$NEDDOC_XSL = tobackslash($NEDDOC_XSL);
+$NEDDOC_PL = tobackslash($NEDDOC_PL);
+
+
+# purge output directory
+if (! -d $outdir)
+{
+    print "creating directory $outdir\n" if $debug;
+    mkdir($outdir) || error("cannot create output directory '$outdir'");
+}
 else
-    if [ $# -eq 0 ]; then
-        echo "opp_neddoc: no input files specified, try . to include all *.ned/*.msg files in current directory" >&2
-        exit 2
-    fi
-    while [ $# -gt 0 ]; do
-        if [ -d "$1" ]; then
-            files="$files `find $1 -name '*.ned' -o -name '*.msg'`" || exit 1
+{
+    delete_recursive($outdir)==0 || error("cannot clean output directory '$outdir' from old files");
+}
+
+print "collecting files...\n" if $verbose;
+if ($all_files eq "")
+{
+    collect_files(".", "$outdir/filelist.txt")==0 || error("error creating the file list");
+}
+else
+{
+    if (@ARGV==())
+    {
+        print STDERR "opp_neddoc: no input files specified, type -h for help\n";
+        exit(2);
+    }
+
+    while (@ARGV)
+    {
+        $arg = tobackslash(shift @ARGV);
+        if (-d "$arg")
+        {
+            collect_files($arg, "$outdir/filelist.txt")==0 || error("error creating the file list");
+        }
         else
-            files="$files $1"
-        fi
-        shift
-    done
-fi
+        {
+            runprog("echo $arg >>".tobackslash("$outdir/filelist.txt"))==0 || error("error creating the file list");
+        }
+    }
+}
 
-echo 'transforming to xml...'
-nedtool -x -e -t -y -m -o $TMPFILE $files || exit 1
+# make file names in filelist.txt relative to current directory; also weed out
+# file names not ending in .ned or .msg (i.e. backup files ending in .ned~0)
+$currentdir = tobackslash(cwd());
+rename("$outdir/filelist.txt", "$outdir/filelist.tmp");
+open FLIN, "$outdir/filelist.tmp";
+open FLOUT, ">$outdir/filelist.txt";
+while (<FLIN>)
+{
+    s/[\r\n]*$//;  # for Cygwin, chomp is not enough
+    next if (!/.ned$/ && !/.msg$/);
+    s|^\Q$currentdir\E[\\/]*||;
+    print FLOUT $_, "\n";
+}
+close FLOUT;
+close FLIN;
+unlink("$outdir/filelist.tmp") if (!debug);
 
-if [ "$screenshots" = "yes" ]; then 
-    if [ -n "$PS2GIF" ]; then
-        echo 'exporting screenshots (Postscript) using GNED...'
-        nedfilesonly=`echo $files | sed 's/[^ ]*\.msg//g'`
-        gned -- -c $outdir $nedfilesonly || exit 1
-        echo 'converting Postscript to GIF using '$PS2GIF'...'
-        for i in $outdir/*.eps; do
-           echo -n '#'
-           gif=`echo $i | sed 's/eps$/gif/'`
-           $PS2GIF $i $gif || exit 1
-        done
-        echo
+#
+# now start the real job
+#
+print "transforming to xml...\n" if $verbose;
+runprog("$NEDTOOL -x -e -t -y -m -o $outdir/inputfiles.xml \@$outdir/filelist.txt")==0 || error("error");
+
+if ($screenshots)
+{
+    if ($GHOSTSCRIPT ne "")
+    {
+        print "exporting screenshots in Postscript using GNED...\n" if $verbose;
+        runprog("$GNED -- -c $outdir -e jpg \@$outdir/filelist.txt >nul")==0 || error("error invoking GNED");
+        print "converting Postscript to JPG with Ghostscript...\n" if $verbose;
+        foreach $i (glob("$outdir/*.eps"))
+        {
+           print "#" if (!$debug && $verbose);
+           $jpg = $i;
+           $jpg =~ s/eps$/jpg/;
+           runprog("$GHOSTSCRIPT -dEPSCrop -sNOPAUSE -sBATCH -sDEVICE=jpeg -sOutputFile=$jpg $i >>$outdir/gs.err")==0 || error("error invoking Ghostscript");
+        }
+        print "\n" if (!$debug && $verbose);
+
+        if (-s "$outdir/gs.err")
+        {
+           print "see Ghostscript warnings in $outdir/gs.err\n" if $verbose;
+        }
+
         # hack: must convert $outdir to absolute path, otherwise xslt will take it
         # as relative to the sylesheet (@#$#@$!!)
-        imagesxml=$outdir/images.xml
-        case $imagesxml in
-          /*) : ;;
-          *) imagesxml=`pwd`/$imagesxml ;;
-        esac
+        $imagesxml = absolutepath("$outdir/images.xml");
+    }
     else
-        echo 'skipping diagram exporting (no Postscript-to-GIF converter configured)'
-        imagesxml=
-    fi
-fi
+    {
+        print "skipping diagram exporting (no Postscript-to-JPG converter configured)" if $verbose;
+        $imagesxml = "";
+    }
+}
 
 # hack: must convert $doxytagfile to absolute path, otherwise xslt will take it
 # as relative to the sylesheet
-if [ -n "$doxytagfile" ]; then
-   case $doxytagfile in
-     /*) : ;;
-     *) doxytagfile=`pwd`/$doxytagfile ;;
-   esac
-fi
+if ($doxytagfile ne "") {
+    $doxytagfile = absolutepath($doxytagfile);
+}
 
-echo 'applying xslt stylesheet...'
-# FIXME xslt outputs lots of blank lines, hence the >/dev/null
-xsltproc --stringparam outputdir "$outdir" \
-         --stringparam imagesxml "$imagesxml" \
-         --stringparam document-unassigned-params "$unassignedpars" \
-         --stringparam have_dot "$have_dot" \
-         --stringparam doxytagfile "$doxytagfile" \
-         --stringparam doxyhtmldir "$doxyhtmldir" \
-         $NEDDOC_XSL $TMPFILE >/dev/null || exit 1
+print "applying XSLT stylesheet...\n" if $verbose;
+$xsltcommand = "$XSLTPROC".
+               " --stringparam outputdir \"".toslash($outdir)."\"".
+               " --stringparam imagesxml \"".toslash($imagesxml)."\"".
+               " --stringparam document-unassigned-params \"".($unassignedpars?"y":"n")."\"".
+               " --stringparam have_dot \"".($have_dot?"y":"n")."\"".
+               " --stringparam doxytagfile \"".toslash($doxytagfile)."\"".
+               " --stringparam doxyhtmldir \"".toslash($doxyhtmldir)."\"".
+               " --output nul".
+               " $NEDDOC_XSL $outdir/inputfiles.xml";
+runprog($xsltcommand)==0 || error("error invoking xsltproc");
 
-if [ "$have_dot" = "yes" ]; then
-    echo 'generating diagrams via '$DOT'...'
-    for i in $outdir/*.dot; do
-       echo -n '#'
-       gif=`echo $i | sed 's/dot$/gif/'`
-       map=`echo $i | sed 's/dot$/map/'`
-       $DOT -Tgif  <$i >$gif 2>>$outdir/dot.err || exit 1
-       $DOT -Tcmap <$i >$map 2>>$outdir/dot.err || exit 1
-       if [ -n "$GIFTRANS" ]; then
-           mv $gif $gif.tmp || exit 1
-           $GIFTRANS -t white $gif.tmp >$gif || exit 1
-           rm $gif.tmp || exit 1
-       fi
-    done
-    echo
-    if [ -s $outdir/dot.err ]; then
-       echo 'see warnings from '$DOT' in '$outdir'/dot.err'
-    fi
-fi
+if ($have_dot)
+{
+    print "generating diagrams via DOT...\n" if $verbose;
+    foreach $i (glob("$outdir/*.dot"))
+    {
+       print "#" if (!$debug && $verbose);
+       $gif = $i; $gif =~ s/dot$/gif/;
+       $map = $i; $map =~ s/dot$/map/;
+       runprog("$DOT -Tgif  <$i >$gif 2>>$outdir/dot.err")==0 || error("error invoking DOT");
+       runprog("$DOT -Tcmap <$i >$map 2>>$outdir/dot.err")==0 || error("error invoking DOT");
+       if ($GIFTRANS ne "")
+       {
+           rename($gif, "$outdir/__tmp.gif");
+           runprog("$GIFTRANS -t \"#ffffff\" $outdir/__tmp.gif >$gif")==0 || error("error invoking giftrans");
+           unlink("$outdir/__tmp.gif");
+       }
+    }
+    print "\n" if (!$debug && $verbose);
+    if (-s "$outdir/dot.err")
+    {
+       print "see warnings from $DOT in $outdir/dot.err\n" if $verbose;
+    }
+}
 
-echo 'formatting comments...'
-perl $NEDDOC_PL $outdir || exit 1
- 
-echo 'documentation created in '$outdir'/ -- start page is index.html'
-cleanup
+print "formatting comments...\n" if $verbose;
+runprog("$PERL $NEDDOC_PL $outdir")==0 || error("error invoking HTML formatter");
+
+if (!$debug)
+{
+    unlink(glob("$outdir/*.eps"));
+    unlink(glob("$outdir/*.dot"));
+    unlink(glob("$outdir/*.map"));
+    unlink("$outdir/inputfiles.xml");
+    unlink("$outdir/images.xml");
+    unlink("$outdir/filelist.txt");
+}
+else
+{
+    print "intermediate files left in $outdir/ (debug mode doesn't delete them)\n";
+}
+
+print "documentation created in $outdir/ -- start page is index.html\n" if $verbose;
 
 
+sub runprog
+{
+    my $prog = shift;
+    print "running: $prog\n" if $debug;
+    system($prog);
+}
+
+sub absolutepath
+{
+    my $filename = tobackslash(shift);
+    if ($isWindows) {
+        # COMSPEC is necessary to prevent getting other "dir" programs in the path
+        $absfilename = `$ENV{COMSPEC} /c dir /s /b $filename`;
+        if ($?) {error("'$filename' does not exist")}
+        chomp($absfilename);
+    } else {
+        $absfilename = $filename;
+        $absfilename = cwd()."/".$filename if (!($filename =~ /^\//));
+        if (! -f $absfilename) {error("'$filename' does not exist");}
+    }
+    $absfilename;
+}
+
+sub error
+{
+    my $msg = shift;
+    print STDERR "opp_neddoc: ", $msg, "\n";
+    exit(2);
+}
+
+sub tobackslash
+{
+    my $f = shift;
+    $f =~ s|/|\\|g if $isWindows;
+    $f;
+}
+
+sub toslash
+{
+    my $f = shift;
+    $f =~ s|\\|/|g;
+    $f;
+}
+
+sub directoryof
+{
+    my $dir = shift;
+    $dir =~ s|[^/\\:]*$||g;
+    $dir = "." if ($dir eq "");
+    $dir;
+}
+
+sub delete_recursive
+{
+    my $dir = tobackslash(shift);
+    if ($isWindows) {
+        # COMSPEC is necessary to prevent getting other "del" programs in the path
+        runprog("$ENV{COMSPEC} /c del /s /q $dir\\* >nul");
+    } else {
+        runprog("rm -rf $dir/*");
+    }
+
+}
+
+sub collect_files
+{
+    my $dir = tobackslash(shift);
+    my $listfile = tobackslash(shift);
+    if ($isWindows) {
+        # COMSPEC is necessary to prevent getting other "dir" programs in the path
+        runprog("$ENV{COMSPEC} /c dir /s /b $dir\\*.ned $dir\\*.msg >>$listfile");
+    } else {
+        runprog("find $dir -name '*.ned' -o -name '*.msg' >>$listfile");
+    }
+}
 
