test: buildtest fixes
- removed build testing in non C++11 mode
- fixed cMPI test
- configfile wariable asserts can recognize VER ?= value format too

X-Committed-on-Branch: master

diff --git a/test/build/test-builds b/test/build/test-builds
--- a/test/build/test-builds
+++ b/test/build/test-builds
@@ -30,7 +30,6 @@ export LIBXML_LIBS=
 export EXPAT_LIBS=
 export CFLAGS_DEBUG=
 export CFLAGS_RELEASE=
-export USE_CXX11=yes
 
 export TWEAKCONFIG="perl $TEST_DIR/tweakconfigfile.pl"
 
@@ -102,7 +101,6 @@ compile_gcc() {
     $TWEAKCONFIG setoradd configure.user LIBXML_LIBS  "$LIBXML_LIBS" || failure $CFG
     $TWEAKCONFIG setoradd configure.user EXPAT_LIBS  "$EXPAT_LIBS" || failure $CFG
     $TWEAKCONFIG setoradd configure.user WITH_SYSTEMC  "$WITH_SYSTEMC" || failure $CFG
-    $TWEAKCONFIG setoradd configure.user USE_CXX11  "$USE_CXX11" || failure $CFG
 
     echo "    Configuring..."
     cp configure.user "$LOG_DIR/$CFG-configure.user"
@@ -134,7 +132,6 @@ compile_vc() {
     $TWEAKCONFIG setoradd configuser.vc WITH_OSG  "$WITH_OSG" || failure $CFG
     $TWEAKCONFIG setoradd configuser.vc SHARED_LIBS  "$SHARED_LIBS" || failure $CFG
     $TWEAKCONFIG setoradd configuser.vc WITH_SYSTEMC  "$WITH_SYSTEMC" || failure $CFG
-    $TWEAKCONFIG setoradd configure.user USE_CXX11  "$USE_CXX11" || failure $CFG
 
     cp configuser.vc "$LOG_DIR/$CFG-configuser.vc"
 
@@ -161,7 +158,6 @@ compile_clang() {
     $TWEAKCONFIG setoradd configure.user LIBXML_LIBS  "$LIBXML_LIBS" || failure $CFG
     $TWEAKCONFIG setoradd configure.user EXPAT_LIBS  "$EXPAT_LIBS" || failure $CFG
     $TWEAKCONFIG setoradd configure.user WITH_SYSTEMC  "$WITH_SYSTEMC" || failure $CFG
-    $TWEAKCONFIG setoradd configure.user USE_CXX11  "$USE_CXX11" || failure $CFG
 
     echo "    Configuring..."
     cp configure.user "$LOG_DIR/$CFG-configure.user"
@@ -179,7 +175,7 @@ compile_clang() {
 
     echo "    Building..."
     $MAKE_PROG cleanall >"$LOG_DIR/$CFG-makeclean.out" 2>"$LOG_DIR/$CFG-makeclean.err" || failure "make cleanall failed - $CFG"
-    $MAKE_PROG >"$LOG_DIR/$CFG-make.out" 2>"$LOG_DIR/$CFG-make.err" || failure "make failed - $CFG"
+    $MAKE_PROG -j8 >"$LOG_DIR/$CFG-make.out" 2>"$LOG_DIR/$CFG-make.err" || failure "make failed - $CFG"
     samples/aloha/aloha -v >"$LOG_DIR/$CFG-buildinfo.out" 2>"$LOG_DIR/$CFG-buildinfo.err"
 }
 
@@ -235,7 +231,7 @@ CFG=default
 (compile)
 
 contains cParsimPartition yes
-contains "Tkenv : graphical user interface" yes
+contains "Tkenv : Tk-based legacy graphical user interface" yes
 contains "Cmdenv : command-line user interface" yes
 contains "Qtenv : Qt-based graphical user interface" yes
 
@@ -267,7 +263,7 @@ CFG=default_static
 (SHARED_LIBS=no compile)
 
 # the static build does not contain opp_run so we must use the aloha sample
-(TEST_PROG="samples/aloha/aloha -h all" contains "Tkenv : graphical user interface" yes)
+(TEST_PROG="samples/aloha/aloha -h all" contains "Tkenv : Tk-based legacy graphical user interface" yes)
 (TEST_PROG="samples/aloha/aloha -h all" contains "Qtenv : Qt-based graphical user interface" yes)
 (TEST_PROG="samples/aloha/aloha -h all" contains "Cmdenv : command-line user interface" yes)
 (TEST_PROG="samples/aloha/aloha -v" contains "XMLPARSER=libxml" yes)
@@ -303,14 +299,9 @@ if [ "$EXTRA_TESTS" != "yes" ]; then
 fi
 
 #########################################
-# check building without C++11 support (disable also QTENV and OSG as they require C++11)
-CFG=without_cpp11
-(WITH_OSG=no WITH_QTENV=no USE_CXX11=no compile)
-
-#########################################
 # check building without OSG
 CFG=without_osg
-(WITH_OSG=no compile)
+(WITH_OSG=no WITH_OSGEARTH=no compile)
 (TEST_PROG="opp_run contains "WITH_OSG" no)
 (runtest makemake 0)
 
